### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by stevetoro** [kavita387/prj-rev-bwfs-dasmoto#3]
https://github.com/kavita387/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L15

Nice job saving these images to your local project directory and using relative file paths to access them. This helps ensure your website always has access to the images it needs. 

Even better job writing an alt attribute for each image, because it makes your website accessible to more people using "non-typical" devices, readers, or browsers. Great attention to detail 👍 

As a side note, you may want to use a different filename than "image1", "image2", etc.

**Comment by kavita387** [comment]
Makes sense! Thanks so much!
