### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by stevetoro** [kavita387/prj-rev-bwfs-dasmoto#5]
Satisfactory 👍 

Your code follows the design specification to the letter basically, and you've written your code with a lot of self awareness. It's organized and easy to adapt or maintain. It also follows best practices by using alt attributes for images, which is a requirement in HTML5. Good job!

You did miss one thing. The paragraph text should also be Helvetica font, but this wasn't actually specified, just shown. 

I recommend you expand on the project. It looks like you're ready to read ahead to more advanced content, like semantic HTML5 elements and even mobile responsiveness. See if you can start researching these topics and produce more semantic code and a website that's pleasant to look at on any screen size.

**Comment by kavita387** [comment]
Thanks for all your feedback!
